package db;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class DbProcessor {
    public static void createDb() throws SQLException {
        try (Connection conn = ConnectionsManager.getConnection(); Statement stat = conn.createStatement()) {
            stat.execute("create table voters(id int generated by default as identity primary key, " +
                    "surname varchar(255), name varchar(255), patronymic varchar(255), passport varchar(255), address varchar(255))");
            stat.execute("create table ballots(id int generated by default as identity primary key, " +
                    "number int not null unique)");
            stat.execute("create table voters_ballots(voter_id int, ballot_id int)");
        }
    }

    public static void deleteDb() throws SQLException {
        try (Connection conn = ConnectionsManager.getConnection(); Statement stat = conn.createStatement()) {
            stat.execute("drop table if exists voters_ballots");
            stat.execute("drop table if exists voters");
            stat.execute("drop table if exists ballots");
        }
    }
}
